repos:
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: python -m nbconvert --ClearOutputPreprocessor.enabled=True --inplace
      - id: pylint
        name: pylint
        entry: pylint --disable=C0114 
        language: system
        types: [python]
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
